import "bootstrap/dist/css/bootstrap.css";
import Navbar from "@/components/Navbar";
import { Provider } from "@/app/context/context-provider";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Students informartion</title>
      </head>
      <body>
        <header>
          <Navbar />
        </header>
        <Provider>{children}</Provider>
        <Footer />
      </body>
    </html>
  );
}
